/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitmap;



public class App {


    public static void main(String[] args) {
        Bitmap bitmap = new Bitmap();
        bitmap.readImage(args[0]);
        bitmap.darken();
        bitmap.write(args[1]);

    }
}
